// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RagAgentConsole.Data;

#nullable disable

namespace RagAgentConsole.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260610121808_RemoveCveSpecificEvaluationFields")]
    partial class RemoveCveSpecificEvaluationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RagAgentConsole.Models.AppSetting", b =>
                {
                    b.Property<int>("AppSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppSettingId"));

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SettingValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppSettingId");

                    b.HasIndex("SettingKey")
                        .IsUnique();

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("RagAgentConsole.Models.KnowledgeDocument", b =>
                {
                    b.Property<int>("KnowledgeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KnowledgeDocumentId"));

                    b.Property<int>("CharacterCount")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExtractedText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Product")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Tags")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("KnowledgeDocumentId");

                    b.HasIndex("ModuleName");

                    b.ToTable("KnowledgeDocuments");
                });

            modelBuilder.Entity("RagAgentConsole.Models.KnowledgeDocumentChunk", b =>
                {
                    b.Property<int>("KnowledgeDocumentChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KnowledgeDocumentChunkId"));

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KnowledgeDocumentId")
                        .HasColumnType("integer");

                    b.HasKey("KnowledgeDocumentChunkId");

                    b.HasIndex("KnowledgeDocumentId");

                    b.ToTable("KnowledgeDocumentChunks");
                });

            modelBuilder.Entity("RagAgentConsole.Models.PushLog", b =>
                {
                    b.Property<int>("PushLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PushLogId"));

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("InstanceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PushType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TargetGroupId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("PushLogId");

                    b.ToTable("PushLogs");
                });

            modelBuilder.Entity("RagAgentConsole.Models.RetrievalEvaluationCaseEntity", b =>
                {
                    b.Property<int>("RetrievalEvaluationCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RetrievalEvaluationCaseId"));

                    b.Property<string>("CaseKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedContentKeywords")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExpectedDocumentTitles")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExpectedMetadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("IsSeeded")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("RetrievalEvaluationCaseId");

                    b.HasIndex("CaseKey")
                        .IsUnique();

                    b.ToTable("RetrievalEvaluationCases");
                });

            modelBuilder.Entity("RagAgentConsole.Models.RuntimeLeadershipLease", b =>
                {
                    b.Property<string>("LeaseName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OwnerInstanceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("RenewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LeaseName");

                    b.ToTable("RuntimeLeadershipLeases");
                });

            modelBuilder.Entity("RagAgentConsole.Models.RuntimeNodeHeartbeat", b =>
                {
                    b.Property<int>("RuntimeNodeHeartbeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuntimeNodeHeartbeatId"));

                    b.Property<string>("AppVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("EnvironmentName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("LastSeenTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ProcessStartedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleSummary")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("RuntimeNodeHeartbeatId");

                    b.HasIndex("InstanceName")
                        .IsUnique();

                    b.ToTable("RuntimeNodeHeartbeats");
                });

            modelBuilder.Entity("RagAgentConsole.Models.SecurityAdvisory", b =>
                {
                    b.Property<int>("SecurityAdvisoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SecurityAdvisoryId"));

                    b.Property<string>("AiSummary")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CveId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal?>("CvssScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("HasRansomwareUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKnownExploited")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSyncedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Product")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredAction")
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("Severity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("SuggestedAction")
                        .HasMaxLength(1600)
                        .HasColumnType("character varying(1600)");

                    b.Property<string>("Tags")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("SecurityAdvisoryId");

                    b.HasIndex("CveId");

                    b.HasIndex("SourceName", "ExternalId")
                        .IsUnique();

                    b.ToTable("SecurityAdvisories");
                });

            modelBuilder.Entity("RagAgentConsole.Models.SecurityAdvisoryChunk", b =>
                {
                    b.Property<int>("SecurityAdvisoryChunkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SecurityAdvisoryChunkId"));

                    b.Property<string>("ChunkKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChunkText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmbeddingJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SecurityAdvisoryId")
                        .HasColumnType("integer");

                    b.HasKey("SecurityAdvisoryChunkId");

                    b.HasIndex("SecurityAdvisoryId");

                    b.ToTable("SecurityAdvisoryChunks");
                });

            modelBuilder.Entity("RagAgentConsole.Models.SyncJobLog", b =>
                {
                    b.Property<int>("SyncJobLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SyncJobLogId"));

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstanceName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Message")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SyncJobLogId");

                    b.ToTable("SyncJobLogs");
                });

            modelBuilder.Entity("RagAgentConsole.Models.TelegramChatSubscription", b =>
                {
                    b.Property<int>("TelegramChatSubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramChatSubscriptionId"));

                    b.Property<string>("AdvisoryKeywords")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ChatTitle")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EnableAdvisoryPush")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MinimumSeverity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("TelegramChatSubscriptionId");

                    b.HasIndex("ChatId")
                        .IsUnique();

                    b.ToTable("TelegramChatSubscriptions");
                });

            modelBuilder.Entity("RagAgentConsole.Models.TelegramUpdateInbox", b =>
                {
                    b.Property<int>("TelegramUpdateInboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TelegramUpdateInboxId"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EnqueuedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IngressNode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("LastUpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingNode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("ProcessingStartedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint");

                    b.HasKey("TelegramUpdateInboxId");

                    b.HasIndex("UpdateId")
                        .IsUnique();

                    b.ToTable("TelegramUpdateInboxes");
                });

            modelBuilder.Entity("RagAgentConsole.Models.KnowledgeDocumentChunk", b =>
                {
                    b.HasOne("RagAgentConsole.Models.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RagAgentConsole.Models.SecurityAdvisoryChunk", b =>
                {
                    b.HasOne("RagAgentConsole.Models.SecurityAdvisory", "Advisory")
                        .WithMany("Chunks")
                        .HasForeignKey("SecurityAdvisoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisory");
                });

            modelBuilder.Entity("RagAgentConsole.Models.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("RagAgentConsole.Models.SecurityAdvisory", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
