namespace CPBLLineBotCloud.Models;

/// <summary>
/// 統一整理節點名稱的 fallback 規則，避免多台 VM 沒另外設值時全部撞成同一個名稱。
/// </summary>
public static class AppRuntimeOptionsExtensions
{
    private static readonly string[] AutoGeneratedInstanceNameMarkers =
    [
        "auto",
        "local-node",
        "docker-node"
    ];

    public static string GetEffectiveInstanceName(this AppRuntimeOptions options)
    {
        var configuredInstanceName = options.InstanceName?.Trim();

        if (!string.IsNullOrWhiteSpace(configuredInstanceName) &&
            !AutoGeneratedInstanceNameMarkers.Contains(configuredInstanceName, StringComparer.OrdinalIgnoreCase))
        {
            return configuredInstanceName;
        }

        var machineName = Environment.MachineName?.Trim();
        return string.IsNullOrWhiteSpace(machineName)
            ? $"node-{Environment.ProcessId}"
            : machineName;
    }

    public static TimeSpan GetLeadershipLeaseDuration(this AppRuntimeOptions options)
    {
        return TimeSpan.FromSeconds(Math.Max(15, options.LeaseDurationSeconds));
    }

    public static TimeSpan GetLeadershipLeaseRenewInterval(this AppRuntimeOptions options)
    {
        var renewIntervalSeconds = Math.Max(5, options.LeaseRenewIntervalSeconds);
        return TimeSpan.FromSeconds(Math.Min(renewIntervalSeconds, (int)options.GetLeadershipLeaseDuration().TotalSeconds));
    }

    public static TimeSpan GetLeadershipLeaseAcquireRetryInterval(this AppRuntimeOptions options)
    {
        return TimeSpan.FromSeconds(Math.Max(3, options.LeaseAcquireRetrySeconds));
    }
}
